packageExtensions:
  "@apollo/client@*":
    dependencies:
      graphql: "*"
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: "*"
  "@apollographql/graphql-language-service-interface@*":
    dependencies:
      graphql: "*"
  "@apollographql/graphql-language-service-parser@*":
    dependencies:
      graphql: "*"
  "@apollographql/graphql-language-service-utils@*":
    dependencies:
      graphql: "*"
  "@babel/runtime@*":
    dependencies:
      core-js: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  "@uppy/image-editor@*":
    dependencies:
      "@uppy/utils": "*"
  "@vue/cli-plugin-typescript@*":
    dependencies:
      babel-loader: "*"
      typescript: "*"
  "@vue/cli-service@*":
    dependencies:
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-e2e-cypress": "*"
      "@vue/cli-plugin-eslint": "*"
      "@vue/cli-plugin-pwa": "*"
      "@vue/cli-plugin-typescript": "*"
      "@vue/cli-plugin-unit-mocha": "*"
      vue-cli-plugin-apollo: "*"
      eslint: "*"
  "@webpack-cli/package-utils@*":
    dependencies:
      cross-spawn: "*"
  apollo-engine-reporting-protobuf@*:
    dependencies:
      long: "*"
  apollo-language-server@*:
    dependencies:
      graphql: "*"
  apollo-link-context@*:
    dependencies:
      graphql: "*"
  apollo-link-error@*:
    dependencies:
      graphql: "*"
  apollo-link-state@*:
    dependencies:
      graphql: "*"
  apollo-link-ws@*:
    dependencies:
      graphql: "*"
  apollo-server-core@*:
    dependencies:
      graphql: "*"
  apollo-server-express@*:
    dependencies:
      graphql: "*"
  apollo-server@*:
    dependencies:
      graphql: "*"
  apollo-upload-client@*:
    dependencies:
      graphql: "*"
  babel-loader@*:
    dependencies:
      "@babel/core": "*"
      "webpack": "*"
  bootstrap-vue@*:
    dependencies:
      vue: "*"
      jquery: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
      vue-template-compiler: "*"
  jwt@*:
    dependencies:
      base64: "*"
  portal-vue@*:
    dependencies:
      vue: "*"
  vue-loader@*:
    dependencies:
      graphql-tag: "*"
      webpack: "*"
      graphql: "*"
  "@vue/babel-plugin-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@vue/cli-plugin-e2e-cypress@*":
    dependencies:
      "eslint": "*"
  "@vue/cli-plugin-unit-mocha@*":
    dependencies:
      "webpack": "*"
  "@graphql-tools/links@*":
    dependencies:
      "subscriptions-transport-ws": "*"
  "apollo-link-http@*":
    dependencies:
      "graphql": "*"
  "lodash-webpack-plugin@*":
    dependencies:
      "webpack": "*"
  "sass-loader@*":
    dependencies:
      "webpack": "*"
  "apollo-link-persisted-queries@*":
    dependencies:
      "graphql": "*"
  "graphql-subscriptions@*":
    dependencies:
      "graphql": "*"
  "graphql-upload@*":
    dependencies:
      "graphql": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

preferInteractive: true

#yarnPath: .yarn/releases/yarn-2.3.3.cjs
